-- Schema of data/campus_customs.db (generated by sync_problem_folders.py)

-- catalogue: 102 rows
CREATE TABLE catalogue (
            product_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            garment_type TEXT NOT NULL,
            description TEXT NOT NULL,
            colors TEXT NOT NULL,
            search_tags TEXT NOT NULL,
            image_file_path TEXT NOT NULL,
            price REAL NOT NULL
        );

-- inventory: 612 rows
CREATE TABLE inventory (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            product_id TEXT NOT NULL,
            size TEXT NOT NULL,
            quantity INTEGER NOT NULL,
            FOREIGN KEY (product_id) REFERENCES catalogue(product_id),
            UNIQUE (product_id, size)
        );

-- users: 3 rows
CREATE TABLE users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT (datetime('now'))
        , first_name TEXT, last_name TEXT);

-- chat_messages: 22 rows
CREATE TABLE chat_messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            role TEXT NOT NULL,
            content TEXT NOT NULL,
            products_json TEXT,
            created_at TEXT NOT NULL DEFAULT (datetime('now')), page_context_json TEXT,
            FOREIGN KEY (user_id) REFERENCES users(id)
        );

-- sessions: 2 rows
CREATE TABLE sessions (
            token_hash TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL,
            created_at TEXT NOT NULL DEFAULT (datetime('now')),
            expires_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id)
        );
